apiVersion: v1
kind: Secret
metadata:
  name: toyota-secrets
  namespace: default
type: Opaque
stringData:
  SA_PASSWORD: "Toyota@2026!"
  JWT_SECRET_KEY: "mi-clave-secreta-super-segura-toyota-2026-256bits!!"
  DB_CONNECTION: "Server=sqlserver-service,1433;Database=ConcesionariaAutosToyota;User Id=sa;Password=Toyota@2026!;TrustServerCertificate=True;"
  RABBITMQ_PASSWORD: "guest"
